// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDYM4sz0GneipO8W5nhFanLcClPJ3Z7Iw',
    appId: '1:810131365389:web:120679da06b36943e77f44',
    messagingSenderId: '810131365389',
    projectId: 'cloud-message-test-1d41b',
    authDomain: 'cloud-message-test-1d41b.firebaseapp.com',
    databaseURL: 'https://cloud-message-test-1d41b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloud-message-test-1d41b.appspot.com',
    measurementId: 'G-Q8ETWEZRKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXjpUAtFNe7h1Ed92ZPUP50SNchyXLEeQ',
    appId: '1:810131365389:android:e7f2ae15f0c80c77e77f44',
    messagingSenderId: '810131365389',
    projectId: 'cloud-message-test-1d41b',
    databaseURL: 'https://cloud-message-test-1d41b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloud-message-test-1d41b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiQbNt3HAIWA6e9hZb4DHDjpZqHix4YIA',
    appId: '1:810131365389:ios:7211715f29ff2a37e77f44',
    messagingSenderId: '810131365389',
    projectId: 'cloud-message-test-1d41b',
    databaseURL: 'https://cloud-message-test-1d41b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloud-message-test-1d41b.appspot.com',
    iosBundleId: 'com.example.suspiciousActionDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiQbNt3HAIWA6e9hZb4DHDjpZqHix4YIA',
    appId: '1:810131365389:ios:7211715f29ff2a37e77f44',
    messagingSenderId: '810131365389',
    projectId: 'cloud-message-test-1d41b',
    databaseURL: 'https://cloud-message-test-1d41b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloud-message-test-1d41b.appspot.com',
    iosBundleId: 'com.example.suspiciousActionDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOuZYTcVJZkh2WL0F_tuc-XG2bbF3UvRI',
    appId: '1:810131365389:web:362ddc4f32cc3c8ae77f44',
    messagingSenderId: '810131365389',
    projectId: 'cloud-message-test-1d41b',
    authDomain: 'cloud-message-test-1d41b.firebaseapp.com',
    databaseURL: 'https://cloud-message-test-1d41b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cloud-message-test-1d41b.appspot.com',
    measurementId: 'G-26RJ0FYNEQ',
  );
}
